name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build site assets
      working-directory: ${{ github.workspace }}
      run: ls -la target
    
    - name: Build Number Generator
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}
    
    - name: Print new build number
      run: echo "Build number iss $BUILD_NUMBER"
    
      
